// testing model schema validations
// using validateSync so no db connection needed

import mongoose from "mongoose";

// importing models - these just register schemas, dont need db
import Invoice from "../../models/invoiceModel.js";
import Payment from "../../models/paymentModel.js";
import User from "../../models/userModel.js";
import Tenant from "../../models/tenantModel.js";

// shortcut for making objectids
const id = () => new mongoose.Types.ObjectId();

// invoice model tests

describe("Invoice model - schema validation", () => {
  const validInvoiceData = () => ({
    tenantId: id(),
    propertyId: id(),
    landlordId: id(),
    amount: 5000,
    type: "Rent",
    dueDate: new Date("2025-01-31"),
  });

  test("valid invoice document passes validation without errors", () => {
    const doc = new Invoice(validInvoiceData());
    const error = doc.validateSync();
    expect(error).toBeUndefined();
  });

  test("requires tenantId", () => {
    const data = validInvoiceData();
    delete data.tenantId;
    const doc = new Invoice(data);
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.tenantId).toBeDefined();
  });

  test("requires propertyId", () => {
    const data = validInvoiceData();
    delete data.propertyId;
    const doc = new Invoice(data);
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.propertyId).toBeDefined();
  });

  test("requires landlordId", () => {
    const data = validInvoiceData();
    delete data.landlordId;
    const doc = new Invoice(data);
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.landlordId).toBeDefined();
  });

  test("requires amount", () => {
    const data = validInvoiceData();
    delete data.amount;
    const doc = new Invoice(data);
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.amount).toBeDefined();
  });

  test("requires type", () => {
    const data = validInvoiceData();
    delete data.type;
    const doc = new Invoice(data);
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.type).toBeDefined();
  });

  test("requires dueDate", () => {
    const data = validInvoiceData();
    delete data.dueDate;
    const doc = new Invoice(data);
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.dueDate).toBeDefined();
  });

  test("rejects invalid type enum value", () => {
    const doc = new Invoice({ ...validInvoiceData(), type: "InvalidType" });
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.type).toBeDefined();
  });

  test("accepts all valid type enum values", () => {
    for (const type of ["Rent", "Maintenance", "Utilities", "Other"]) {
      const doc = new Invoice({ ...validInvoiceData(), type });
      const error = doc.validateSync();
      expect(error).toBeUndefined();
    }
  });

  test("rejects invalid status enum value", () => {
    const doc = new Invoice({ ...validInvoiceData(), status: "Unpaid" });
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.status).toBeDefined();
  });

  test("accepts all valid status enum values: Pending, Paid, Overdue", () => {
    for (const status of ["Pending", "Paid", "Overdue"]) {
      const doc = new Invoice({ ...validInvoiceData(), status });
      const error = doc.validateSync();
      expect(error).toBeUndefined();
    }
  });

  test("defaults status to Pending", () => {
    const doc = new Invoice(validInvoiceData());
    expect(doc.status).toBe("Pending");
  });

  test("defaults autoGenerated to false", () => {
    const doc = new Invoice(validInvoiceData());
    expect(doc.autoGenerated).toBe(false);
  });

  test("rejects invalid splitMethod in utilityBill", () => {
    const doc = new Invoice({
      ...validInvoiceData(),
      utilityBill: { splitMethod: "invalid-method" },
    });
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors["utilityBill.splitMethod"]).toBeDefined();
  });

  test("accepts all valid splitMethod values in utilityBill", () => {
    for (const splitMethod of ["equal", "room-size", "occupancy", "custom"]) {
      const doc = new Invoice({
        ...validInvoiceData(),
        utilityBill: { splitMethod },
      });
      const error = doc.validateSync();
      expect(error).toBeUndefined();
    }
  });

  test("breakdown defaults all utility subfields to 0", () => {
    const doc = new Invoice(validInvoiceData());
    expect(doc.breakdown.baseRent).toBe(0);
    expect(doc.breakdown.utilities.electricity).toBe(0);
    expect(doc.breakdown.utilities.water).toBe(0);
    expect(doc.breakdown.utilities.gas).toBe(0);
    expect(doc.breakdown.totalUtilities).toBe(0);
  });

  test("accepts paidDate as a Date", () => {
    const doc = new Invoice({ ...validInvoiceData(), paidDate: new Date() });
    const error = doc.validateSync();
    expect(error).toBeUndefined();
    expect(doc.paidDate).toBeInstanceOf(Date);
  });
});

// payment model tests

describe("Payment model - schema validation", () => {
  const validPaymentData = () => ({
    invoiceId: id(),
    tenantId: id(),
    userId: id(),
    amount: 5000,
    gateway: "khalti",
  });

  test("valid payment document passes validation without errors", () => {
    const doc = new Payment(validPaymentData());
    const error = doc.validateSync();
    expect(error).toBeUndefined();
  });

  test("requires invoiceId", () => {
    const data = validPaymentData();
    delete data.invoiceId;
    const doc = new Payment(data);
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.invoiceId).toBeDefined();
  });

  test("requires tenantId", () => {
    const data = validPaymentData();
    delete data.tenantId;
    const doc = new Payment(data);
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.tenantId).toBeDefined();
  });

  test("requires userId", () => {
    const data = validPaymentData();
    delete data.userId;
    const doc = new Payment(data);
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.userId).toBeDefined();
  });

  test("requires amount", () => {
    const data = validPaymentData();
    delete data.amount;
    const doc = new Payment(data);
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.amount).toBeDefined();
  });

  test("requires gateway", () => {
    const data = validPaymentData();
    delete data.gateway;
    const doc = new Payment(data);
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.gateway).toBeDefined();
  });

  test("rejects invalid gateway value", () => {
    const doc = new Payment({ ...validPaymentData(), gateway: "paypal" });
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.gateway).toBeDefined();
  });

  test("accepts esewa as a valid gateway", () => {
    const doc = new Payment({ ...validPaymentData(), gateway: "esewa" });
    const error = doc.validateSync();
    expect(error).toBeUndefined();
  });

  test("accepts khalti as a valid gateway", () => {
    const doc = new Payment({ ...validPaymentData(), gateway: "khalti" });
    const error = doc.validateSync();
    expect(error).toBeUndefined();
  });

  test("defaults status to initiated", () => {
    const doc = new Payment(validPaymentData());
    expect(doc.status).toBe("initiated");
  });

  test("rejects invalid status enum value", () => {
    const doc = new Payment({ ...validPaymentData(), status: "processing" });
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.status).toBeDefined();
  });

  test("accepts all valid status values", () => {
    for (const status of ["initiated", "pending", "completed", "failed", "refunded"]) {
      const doc = new Payment({ ...validPaymentData(), status });
      const error = doc.validateSync();
      expect(error).toBeUndefined();
    }
  });

  test("accepts optional failureReason string", () => {
    const doc = new Payment({ ...validPaymentData(), failureReason: "User cancelled" });
    const error = doc.validateSync();
    expect(error).toBeUndefined();
    expect(doc.failureReason).toBe("User cancelled");
  });
});

// user model tests

describe("User model - schema validation", () => {
  const validUserData = () => ({
    name: "Alice Sharma",
    email: "alice@example.com",
    password: "hashedpassword123",
    phone: "9800012345",
  });

  test("valid user document passes validation", () => {
    const doc = new User(validUserData());
    const error = doc.validateSync();
    expect(error).toBeUndefined();
  });

  test("requires name", () => {
    const data = validUserData();
    delete data.name;
    const doc = new User(data);
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.name).toBeDefined();
  });

  test("requires email", () => {
    const data = validUserData();
    delete data.email;
    const doc = new User(data);
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.email).toBeDefined();
  });

  test("requires password", () => {
    const data = validUserData();
    delete data.password;
    const doc = new User(data);
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.password).toBeDefined();
  });

  test("requires phone", () => {
    const data = validUserData();
    delete data.phone;
    const doc = new User(data);
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.phone).toBeDefined();
  });

  test("defaults role to tenant", () => {
    const doc = new User(validUserData());
    expect(doc.role).toBe("tenant");
  });

  test("rejects invalid role value", () => {
    const doc = new User({ ...validUserData(), role: "superuser" });
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.role).toBeDefined();
  });

  test("accepts all valid roles: landlord, tenant, admin", () => {
    for (const role of ["landlord", "tenant", "admin"]) {
      const doc = new User({ ...validUserData(), role });
      const error = doc.validateSync();
      expect(error).toBeUndefined();
    }
  });

  test("defaults isActive to true", () => {
    const doc = new User(validUserData());
    expect(doc.isActive).toBe(true);
  });

  test("defaults isEmailVerified to false", () => {
    const doc = new User(validUserData());
    expect(doc.isEmailVerified).toBe(false);
  });

  test("defaults is2faEnabled to false", () => {
    const doc = new User(validUserData());
    expect(doc.is2faEnabled).toBe(false);
  });

  test("stores optional 2FA fields", () => {
    const twoFactorCode = "123456";
    const twoFactorExpires = new Date(Date.now() + 10 * 60 * 1000);
    const doc = new User({ ...validUserData(), twoFactorCode, twoFactorExpires });
    const error = doc.validateSync();
    expect(error).toBeUndefined();
    expect(doc.twoFactorCode).toBe(twoFactorCode);
  });
});

// tenant model tests

describe("Tenant model - schema validation", () => {
  const validTenantData = () => ({
    userId: id(),
    propertyId: id(),
    unitId: id(),
    monthlyRent: 8000,
    leaseStart: new Date("2025-01-01"),
    leaseEnd: new Date("2026-01-01"),
  });

  test("valid tenant document passes validation", () => {
    const doc = new Tenant(validTenantData());
    const error = doc.validateSync();
    expect(error).toBeUndefined();
  });

  test("requires userId", () => {
    const data = validTenantData();
    delete data.userId;
    const doc = new Tenant(data);
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.userId).toBeDefined();
  });

  test("requires propertyId", () => {
    const data = validTenantData();
    delete data.propertyId;
    const doc = new Tenant(data);
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.propertyId).toBeDefined();
  });

  test("requires unitId", () => {
    const data = validTenantData();
    delete data.unitId;
    const doc = new Tenant(data);
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.unitId).toBeDefined();
  });

  test("requires monthlyRent", () => {
    const data = validTenantData();
    delete data.monthlyRent;
    const doc = new Tenant(data);
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.monthlyRent).toBeDefined();
  });

  test("requires leaseStart", () => {
    const data = validTenantData();
    delete data.leaseStart;
    const doc = new Tenant(data);
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.leaseStart).toBeDefined();
  });

  test("requires leaseEnd", () => {
    const data = validTenantData();
    delete data.leaseEnd;
    const doc = new Tenant(data);
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.leaseEnd).toBeDefined();
  });

  test("defaults status to Pending", () => {
    const doc = new Tenant(validTenantData());
    expect(doc.status).toBe("Pending");
  });

  test("rejects invalid status enum value", () => {
    const doc = new Tenant({ ...validTenantData(), status: "Inactive" });
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.status).toBeDefined();
  });

  test("accepts valid status values: Active, Past, Pending", () => {
    for (const status of ["Active", "Past", "Pending"]) {
      const doc = new Tenant({ ...validTenantData(), status });
      const error = doc.validateSync();
      expect(error).toBeUndefined();
    }
  });

  test("rejects negative securityDeposit", () => {
    const doc = new Tenant({ ...validTenantData(), securityDeposit: -100 });
    const error = doc.validateSync();
    expect(error).toBeDefined();
    expect(error.errors.securityDeposit).toBeDefined();
  });

  test("defaults securityDeposit to 0", () => {
    const doc = new Tenant(validTenantData());
    expect(doc.securityDeposit).toBe(0);
  });

  test("accepts valid securityDeposit of 0", () => {
    const doc = new Tenant({ ...validTenantData(), securityDeposit: 0 });
    const error = doc.validateSync();
    expect(error).toBeUndefined();
  });
});
